[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.30"
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
eth_rpc_url = "https://ethereum-sepolia-rpc.publicnode.com"
